### ISSUE TITLE
Unable to open .DMG file on MacOS 10.11, "No mountable file systems found"

### ISSUE THREAD

**Issue by TIny-Hacker** [CE-Programming/CEmu#389] opened 2021-04-09 15:15 UTC
What's wrong, and with what software version?
---------------------------------------------
Operating System: MacOS 10.11 El Capitan
CEmu Version: 1.3 
Error: I am unable to open the DMG file to install CEmu. Whenever I open it, I get an error: "No mountable file systems found". I have attempted to install it with Homebrew as well, and also to mount the Disk Image with the command line, but neither of those worked either. I have downloaded the DMGs multiple times and in different browsers, and I also received the same error.

What are the steps to reproduce this issue?
-------------------------------------------
1. Download the latest version of CEmu, 1.3
2. Open the DMG file

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
Error message from Homebrew:
```Error: Failure while executing; `hdiutil attach -plist -nobrowse -readonly -mountrandom /var/folders/rj/r862vbv51jgb7tcmv0yb1kxw0000gn/T/d20210409-14362-gpqkbf /var/folders/rj/r862vbv51jgb7tcmv0yb1kxw0000gn/T/d20210409-14362-gpqkbf/0b496264e377afaf36d3b47b37ec6528586c029d9da5cb08f6051256904bdc47--macOS_CEmu.cdr` exited with 1. 
Here's the output:
hdiutil: attach failed - no mountable file systems```

I also cannot build from source, since I can't install Qt5 on El Capitan.

**Comment by jacobly0** [comment] 2021-04-09 15:47
Duplicate of #386.

**Closed by jacobly0** 2021-04-09 15:47 UTC
