### ISSUE TITLE
Sending files from CEmu to flash drive error

### ISSUE THREAD

**Issue by the4thCuber** [CE-Programming/CEmu#440] opened 2022-10-21 22:41 UTC
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
OS: MacOS
CEmu version: 1.3, git hash=87c3b43  
The issue is that, whenever I try to send files from CEmu to local storage, they end up as .` files, unopenable by any apps.
 

What are the steps to reproduce this issue?
-------------------------------------------
1. Send a .8xg to CEmu via 'send to calculator', from flash drive (this is what I tried, I don't know if it works from the computer's hard drive)
2. Ungroup the group on CEmu.
3. Do the 'view variables' option and select all the ungrouped programs
4. In 'save as', navigate to correct folder in flash drive and save.
5. Navigate to the same folder in Finder, and the files just saved are all .` files.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
No

**Comment by Iamaprogramador** [comment] 2022-10-21 22:45
Sorry, actually they are .' files, if that matters.

**Comment by adriweb** [comment] 2022-10-21 23:01
What are the file names in the group? Do they show up correctly in CEmu?
(Both in the calc and in the variables dock)

Could you upload the 8xg here? (You might have to .zip it first)
-- 
Thank you,
Adrien Bertrand

**Comment by Iamaprogramador** [comment] 2022-10-28 22:01
The files show up correctly in CEmu, the problem is that they don't transfer back properly when uploaded.
Here is the group file: [A121421.8xg.zip](https://github.com/CE-Programming/CEmu/files/9892182/A121421.8xg.zip)
Note that I have not tried any other group files.

**Comment by adriweb** [comment] 2024-10-08 09:39
This issue doesn't seem to exist anymore (try the latest release), closing.

**Closed by adriweb** 2024-10-08 09:39 UTC
