### ISSUE TITLE
How do I show menu bar?

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [CE-Programming/CEmu#413] opened 2021-12-04 04:32 UTC
I accidentally clicked, hide menu bar, but now I can't find a way to show it again. Please help.

edit: neverminded, just right-click the screen. (keeping this open in case someone else runs into the same issue)

**Comment by jacobly0** [comment] 2021-12-04 05:19
Duplicate of #391.

**Closed by jacobly0** 2021-12-04 05:19 UTC
