### ISSUE TITLE
Unable to open file after CEmu Restart

### ISSUE THREAD

**Issue by MggMuggins** [CE-Programming/CEmu#123] opened 2017-08-31 01:14 UTC
I've got the emulator running very nicely. The only problem that I'm having is that after restarting it (the emulator, _not_ just the calculator running in the emulator), loading files does not work anymore. I've tracked the problem down to the "Automatically save and restore state" option in the settings tile. I have to uncheck this option and then restart the emulator in order to upload programs again. I'm more than willing to help with the debugging process here.

**Comment by mateoconlechuga** [comment] 2017-08-31 05:12
This is because a state was entered within the emulated calculator where it would not allow sending of files. Simply select `Calculator > Reload ROM` from the menubar. This is not a bug; it is just how emulation works. Good luck :)

Closed as `invalid`

**Closed by mateoconlechuga** 2017-08-31 05:12 UTC

**Comment by MggMuggins** [comment] 2017-08-31 16:35
Thanks!
