### ISSUE TITLE
Saving and Restoring State

### ISSUE THREAD

**Issue by JaroslavN** [CE-Programming/CEmu#14] opened 2016-02-03 14:29 UTC
So ,everytime when i start the emulator ,it says "ram cleared" is it a bug or not?
( for people who are making programs trough the emulator , and when they log on its cleared :l )

ps; how its going for the TI-nspire CX ;)

**Comment by debrouxl** [comment] 2016-02-03 15:17
It's not a bug, just a missing feature: for now, the emulator's state is not saved and restored ;)
Saving and restoring state will be implemented at some point. For now, save your programs on your computer, through the Variables tab, and restore them later.

**Comment by MateoConLechuga** [comment] 2016-02-04 02:09
Keeping this issue open and assigning it as an enhancement: Saving and restoring state.

**Comment by MateoConLechuga** [comment] 2016-02-18 03:20
Completed with commit 48da9b6

**Closed by MateoConLechuga** 2016-02-18 03:20 UTC
Labels: enhancement
