### ISSUE TITLE
Hid the top menu bar by accident and now I have no idea how to get it back.

### ISSUE THREAD

**Issue by devskyfiat** [CE-Programming/CEmu#421] opened 2022-05-16 01:31 UTC
---------------------------------------------
**Operating System:** …   Windows 10
**CEmu version:** … (see in the `About CEmu` menu)  ------ Can't. menu bar is hidden
Hid the top menu bar by accident and now I have no idea how to get it back.
… (including, if applicable what you expect vs. what happens)  

What are the steps to reproduce this issue?
-------------------------------------------
1. … Hid the top menu bar by accident and now I have no idea how to get it back.
2. …
3. …

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…

**Comment by jacobly0** [comment] 2022-05-16 01:32
Duplicate of https://github.com/CE-Programming/CEmu/issues/391.

**Closed** 2022-05-16 01:32 UTC
