### ISSUE TITLE
Restore menu bar and dock

### ISSUE THREAD

**Issue by bethhentges** [CE-Programming/CEmu#431] opened 2022-08-24 21:39 UTC
Hi all,

I downloaded the most recent stable version today, 8/24/2022.

I just installed and ran CEmu for the TI-84 CE.

I have two questions.

**Question 1 **

I hid the menu bar.  How do I get it back?

**Question 2**

I closed each of the dockable things like Keypad and Settings, etc.  

I am able to right-click and choose each of them, but then they open as "free-floating" windows that are not docked.
How do I re-dock them?

Thanks,
Beth
---------------------------------------------
Windows 10 Enterprise

**Comment by adriweb** [comment] 2022-08-25 20:51
Duplicate of #391.

Regarding re-docking things, you should be able to move them around where they get docked, assuming you have enough space, and that UI Edit Mode is enabled of course.

**Closed by adriweb** 2022-08-25 20:51 UTC
Labels: question, GUI
